### ISSUE TITLE
Input Error

### ISSUE THREAD

**Issue by VirtualAI** [simontomaskarlsson/CycleGAN-Keras#11]
Hello,
right after starting the code the gpu init this error appears:

ValueError: Error when checking input: expected input_5 to have 4 dimensions, but got array with shape (1, 193, 193, 1, 3)

(the images are a own dataset having 193x193 pixels)

If i use the official zebra horse images, an different error appears.
Any idea?

Thnak you very much

**Comment by VirtualAI** [comment]
PS: if i set input shape to 193, 193, 3 for color .jpg images of size 193x193, a new error appears:
expected input_6 to have 4 dimensions, but got array with shape (1, 1)

**Comment by simontomaskarlsson** [comment]
Hi @VirtualAI,

The model does not work with all image sizes since some operations by keras, that are done when the image propagates, might have to pad the image in order to compile.

You can manually calculate backwards through the model to see if an image size will work but it is perhaps easier to try with sizes close to 193x193x3, and then rescale or crop the dataset images to a size that works.

The zebra horse dataset with 256x256x3 pixel images should work right away as long as all images are placed in the correct folders. What error do you get?

**Comment by nalibjchn** [comment]
Hi @VirtualAI and @simontomaskarlsson:
I used "apple2orange" (256x256x3), so I got the issue which is the same as @VirtualAI, tan, I updated the initial values, image_shape= (256x1, 256x1, _**3**_). it works now. 
def __init__(self, lr_D=2e-4, lr_G=2e-4, image_shape=(256x1, 256x1, 3),
                 date_time_string_addition='_test', image_folder='apple2orange'):

so I suggest you @VirtualAI to update the value, and if you would like to use your own data wif the different pixels, like 193, you may resize it and train.

**Comment by simontomaskarlsson** [comment]
Thank you for your comment @lindalibjchn, hope this works for you also @VirtualAI.

I do however not recognise this and I'm suspecting it depends on the keras and tensorflow versions. I last trained a model a year ago and framework updates that affect this might have been made since then.

**Comment by VirtualAI** [comment]
thanks, with orange data it worked, so own data set adatped worked  too.
