### ISSUE TITLE
Histogram 

### ISSUE THREAD

**Issue by kpagels** [simontomaskarlsson/CycleGAN-Keras#26]
Hi Simon, 

I noticed you are showing some histogram for your MRI CycleGAN. How exactly did you do this? I assume you generated the images using your model and then made a histogram of that. 

Did you save the python code for this? I couldnt find it in your repository. 

Thanks!

**Comment by simontomaskarlsson** [comment]
Hi,

Yes, I just stored a merged image of a test image in domain A and its corresponding image in domain B (paired data in this case) together with the result of a translation attempt by the the A-to-B generator every epoch. I then stored the images and made a python script where I used some, don't remember the name,  library to plot the histogram of the translated image and the one for the domain B image, and merged the plot with the images.

Regards,
Simon

**Comment by kpagels** [comment]
Ah makes sense. Thanks. Ill try that. 😊

**Comment by simontomaskarlsson** [comment]
Forgot to mention that I unfortunately do not have the script anymore. Luckily I believe, if you haven't change it, that images have been stored during the training process that you can use without the need to alter the code and retrain.

Note also the error that I got in the histograms should be fixed by [this PR](https://github.com/simontomaskarlsson/CycleGAN-Keras/pull/2), so you might very well get nicer looking histograms than I did!

**Comment by kpagels** [comment]
Ok thanks. Yes I normalized my data to -1,1. I never got your function toimage to work though because of old packages and stuff. But I get the idea, ill try if it gives me something. :) Thanks. 

I keep you busy :)
