### ISSUE TITLE
Dimension error after 1 epoch

### ISSUE THREAD

**Issue by APhun** [simontomaskarlsson/CycleGAN-Keras#7]
First of all, thanks for the implement in Keras. It reduces my workload a lot. However I've got a problem.
The size of images in my dataset is 256x256x1, and I changed the image_shape.  After the first epoch is done and message is "saving images for epoch1", an error occurs with " Error when checking input: expected input_5 to have 4 dimensions, but got array with shape (1,256,256,1,3)". I have no idea with this error message.
Should I just to load the image just as 256x256x3 or if I didn't set the correct initialization?

**Comment by simontomaskarlsson** [comment]
Hi @APhun,

Sounds like you did everything right and that this is an error in the code. This since you should be able to use grayscale images if you want to. If you have color images (e.g. rgb) you want to use the size 256x256x3 but as you suggest it can work for you also even if you have grayscale images. The downside is that training takes more time.

On which row in the code is the error thrown?
My guess is that there is a problem in the saveImages-function on row 665-711 and that the if-statements on row 684 and 695 `if self.channels == 1:  # Use the paired data for MR images` should not be there. So you could try to  modify the code by removing rows 684-688 and 695-699.

**Comment by APhun** [comment]
Thanks a lot. The error didn't occur any more. 
By the way, I noticed the comment “for MR images”, I guess you are also studying medical images :)

**Comment by simontomaskarlsson** [comment]
That is correct 👍 Check out https://github.com/simontomaskarlsson/GAN-MRI and https://arxiv.org/abs/1806.07777 to see a part of the research. I've studied both medical MR images and street view rgb images using this implementation of CycleGAN. 

Always fun to meet new people in the merged deep learning and medtech field!

**Comment by APhun** [comment]
Oops😭 the same mistake occurs when I generate synthetic images (training have done and using load_model_and_generate_synthetic_images). I tried to find the solution but I failed.
Do you have any idea to solve it?

**Comment by APhun** [comment]
I think I have solve the problem.
In load_data.py, line 53 should be changed into
'image = np.array(Image.open(os.path.join(image_path, image_name)).convert('L'))'
Because the default mode of 'Image.open()' to load images is 'RGB'.
Maybe it is the same solution to this issue😀 (i didn't try yet)
